version: v1alpha
name: "dealers360-dummy-model"
layer: user
type: lens
tags:
  - lens
description: This semantic model provides dummy model for deakers_360 data product.
lens:
  compute: runnable-default
  #secrets:
   # - name: bitbucket-cred-np
      #allKeys: true
  source:
    type: minerva
    name: miniature
    catalog: icebase
  repo:
    url: https://github.com/mrabhishekb/dealers_360_dummy
    lensBaseDir: dealers_360_dummy/model
    syncFlags:
      - --ref=main

  api:   # optional
    replicas: 3 # optional
    logLevel: Info  # optional
    envs:
      LENS2SQL_DB_QUERY_TIMEOUT: 600
      LENS2SQL_AUTH_EXPIRE_SECS: 3600
    resources: # optional
      requests:
        cpu: 1000m
        memory: 2500Mi
      limits:
        cpu: 6000m
        memory: 8000Mi
  worker: # optional
    replicas: 2 # optional
    logLevel: Info  # optional
    envs:
      LENS2SQL_DB_QUERY_TIMEOUT: 600
      LENS2SQL_AUTH_EXPIRE_SECS: 3600
    resources: # optional
      requests:
        cpu: 1000m
        memory: 2500Mi
      limits:
        cpu: 6000m
        memory: 8000Mi
  router: # optional
    logLevel: info  # optional
    envs:
      LENS2SQL_DB_QUERY_TIMEOUT: 600
      LENS2SQL_AUTH_EXPIRE_SECS: 3600
    resources: # optional
      requests:
        cpu: 1000m
        memory: 2500Mi
      limits:
        cpu: 6000m
        memory: 8000Mi








